// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	dto_passanger "fww-core/internal/data/dto_passanger"

	mock "github.com/stretchr/testify/mock"
)

// Adapter is an autogenerated mock type for the Adapter type
type Adapter struct {
	mock.Mock
}

// CheckPassangerInformations provides a mock function with given fields: data
func (_m *Adapter) CheckPassangerInformations(data *dto_passanger.RequestBPM) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto_passanger.RequestBPM) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestPayment provides a mock function with given fields: data
func (_m *Adapter) RequestPayment(data interface{}) {
	_m.Called(data)
}

// SendNotification provides a mock function with given fields: data
func (_m *Adapter) SendNotification(data interface{}) {
	_m.Called(data)
}

type mockConstructorTestingTNewAdapter interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdapter creates a new instance of Adapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdapter(t mockConstructorTestingTNewAdapter) *Adapter {
	mock := &Adapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
